# Generated by Django 2.2.28 on 2025-02-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_deleteduser_user_id'),
        ('profiles', '0015_auto_20250203_0336'),
    ]

    operations = [
    ]
