# Generated by Django 2.2.28 on 2025-03-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20250321_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名'),
        ),
    ]
