# Generated by Django 2.2.28 on 2025-04-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3boto3
import utils.data
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0020_user_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_when', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=utils.data.PathWrapper('solution_pdfs'))),
                ('file_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('key', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('upload_completed_successfully', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_pdfs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_pdfs', to='profiles.Organization')),
            ],
        ),
    ]
