# Generated by Django 2.2.28 on 2025-04-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0051_merge_20241203_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='profiles.Organization'),
        ),
    ]
